### ISSUE TITLE
Fails to download ICU

### ISSUE THREAD

**Issue by xloem** [jahnog/tensorflow-32-bits-linux#3]
https://github.com/tensorflow/tensorflow/issues/43894

Apparently this was fixed in tensorflow 1.14, so a cherrypick or minor fast-forward might fix it.

**Comment by jahnog** [comment]
Hi @xloem , unfortunately I'm not maintaining a guide to compile tensorflow for windows 32 bits nor doing any maintenance in tensorflow itself.

**Comment by xloem** [comment]
Uh ... thanks for this guide you have that you state you are not maintaining.  Do you think you would merge pull requests to it, despite not maintaining it, or would interested parties need to fork it?

**Comment by jahnog** [comment]
Hi @xloem, feel free to create a pull request or to fork this repo. The issue is that I don't understand what are your intentions regarding this Tensorflow Issue: https://github.com/tensorflow/tensorflow/issues/43894 . I'm not a Tensorflow maintainer nor I have any connection with the Tensorflow team.

**Comment by xloem** [comment]
Sorry, that's just a clear description of the current issue to read more.  Likely it would just mean another step to the build instructions here to include an old fix.
